version: '3.7'
services:
  nginx:
    image: nginx:1.25.3-alpine
    ports:
      - 8888:80
    volumes:
      - ./html:/usr/share/nginx/html/
      - ./config/nginx.conf:/etc/nginx/nginx.conf
      - ./config/default.conf:/etc/nginx/conf.d/default.conf
    restart: always
  backend:
    image: ealen/echo-server
    ports:
      - 8080:80
